#!/usr/bin/env node
/* audit-stories.js — produce a reproducible story-quality audit pack.
 *
 * Ages 2/4/6/8/10/12. Five stories per age with deliberately varied picks
 * (rotates through pools so we don't just stress one combo). Ages 6+ route
 * through v3 (the target path for stronger content) with random blueprint
 * selection. Output is markdown.
 *
 * Usage:
 *   node scripts/audit-stories.js > docs/story-quality-audit-<version>.md
 *
 * Header version is read from APP_VERSION in src/content.js so the audit pack
 * always labels itself with the live release (fixed in v2.7.2 — the header
 * previously hard-coded "v2.7.0 baseline" regardless of current version).
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const content  = fs.readFileSync(path.join(ROOT, 'src/content.js'), 'utf8');
const engineV2 = fs.readFileSync(path.join(ROOT, 'src/engine-v2.js'), 'utf8');
const versionMatch = content.match(/APP_VERSION\s*=\s*['"]([^'"]+)['"]/);
const CURRENT_VERSION = versionMatch ? versionMatch[1] : 'unknown';

const harness = `
global.window = global;
global.localStorage = { getItem: () => null, setItem: () => {} };
${content}
const state = { sidekicks: [], pottyMode: false, teenUnlocked: false, name: 'Cole', setting: 'surprise' };
${engineV2}
return { generateStoryV2, generateStoryV3, WORD_BANK };
`;
const ctx = (new Function(harness))();
const strip = t => String(t).replace(/\[(name|c|y):([^\]]+)\]/g, '$2');

function tierFor(age) {
  if (age <= 3) return 'tot';
  if (age <= 5) return 'little';
  if (age <= 7) return 'kid';
  if (age <= 10) return 'big';
  return 'tween';
}

/* Deterministic varied-pick generator: rotates through each round's options
   by sample-index so 5 samples each draw different choices. */
function pickForSample(tier, sampleIdx) {
  const rounds = ctx.WORD_BANK[tier] || [];
  const out = {};
  for (const r of rounds) {
    if (!r.options || !r.options.length) continue;
    const opt = r.options[(sampleIdx * 3 + r.cat.length) % r.options.length];
    out[r.cat] = { w: opt.w };
  }
  // Vary freeword/freeword2 deterministically too
  const FREEWORDS  = ['KABLAM','WHOOSH','BOINGO','YOWZA','SPLAT','BONK'];
  const FREEWORDS2 = ['BOINGO','KAPOW','ZONK','HUZZAH','OOOMPH','YIP'];
  out.freeword  = { w: FREEWORDS[sampleIdx % FREEWORDS.length],  subtype: 'shout' };
  out.freeword2 = { w: FREEWORDS2[sampleIdx % FREEWORDS2.length] };
  return out;
}

const SETTINGS = ['surprise','diner','mall','football','school','backyard','grocery','zoo','bus'];
function settingForSample(sampleIdx) { return SETTINGS[sampleIdx % SETTINGS.length]; }

const BLUEPRINTS = ['lost_snack_v3','goal_spine_v3','show_wrong_v3','rule_loophole_v3'];

const AGES = [2, 4, 6, 8, 10, 12];

console.log(`# Story Quality Audit — ${CURRENT_VERSION}\n`);
console.log('Reproducible audit pack. Generated by `scripts/audit-stories.js`.');
console.log('Ages 2/4/6/8/10/12 × 5 stories each = 30 stories total.');
console.log('Ages 6+ route through v3 (random blueprint per story). Picks vary deterministically per sample index.\n');
console.log('Scoring rubric (1-5):');
console.log('- **Humor** — does this make a kid laugh?');
console.log('- **Substance** — is there a real arc (setup → problem → action → payoff)?');
console.log('- **Kid agency** — is the kid the driver, not the witness?');
console.log('- **Choice integration** — are chosen words load-bearing or decoration?');
console.log('- **Rereadability** — would the kid ask for "again"?');
console.log('- **Age fit** — vocabulary and complexity right for the age?\n');
console.log('---\n');

for (const age of AGES) {
  const tier = tierFor(age);
  console.log(`## Age ${age} (${tier})\n`);
  for (let s = 0; s < 5; s++) {
    const picks   = pickForSample(tier, s);
    const setting = settingForSample(s);
    picks.setting = { id: setting };
    let story, source;
    if (age >= 6) {
      // Force varied blueprint per sample so we get all 4 represented
      picks.__v3BlueprintId = BLUEPRINTS[s % BLUEPRINTS.length];
      story = ctx.generateStoryV3('Cole', picks, age);
      source = 'v3 ' + picks.__v3BlueprintId;
    } else {
      story = ctx.generateStoryV2('Cole', picks, age);
      source = 'v2 ' + tier;
    }
    const pickSummary = ['pet','food','place','creature','color','move','mood','sky','weather']
      .filter(k => picks[k]).map(k => `${k}=${picks[k].w}`).join(' / ');
    console.log(`### Sample ${s + 1} — engine=${source}, setting=${setting}`);
    console.log(`**Picks:** ${pickSummary}`);
    console.log(`**Freewords:** ${picks.freeword.w} / ${picks.freeword2.w}\n`);
    if (!story) {
      console.log('_NULL — engine returned no story._\n');
      continue;
    }
    console.log(`**Title:** ${strip(story.title)}\n`);
    story.paragraphs.forEach((p, i) => console.log(`P${i + 1}: ${strip(p)}\n`));
    console.log('**Scores (pre-change):**');
    console.log('- Humor: TBD');
    console.log('- Substance: TBD');
    console.log('- Kid agency: TBD');
    console.log('- Choice integration: TBD');
    console.log('- Rereadability: TBD');
    console.log('- Age fit: TBD\n');
    console.log('**Notes:** TBD\n');
    console.log('---\n');
  }
}
